const cates = ['精选', '女装', '男装', '内衣', '美妆', '配饰', '鞋品', '箱包', '儿童', '母婴', '居家', '美食', '数码', '家电', '其他', '车品', '文体', '宠物'];
// 0全部，1是母婴童品，2百变女装，3是食品酒水，4是居家日用，5是美妆洗护，6是品质男装，7是舒适内衣，8是箱包配饰，9是男女鞋靴，10是宠物用品，11是数码家电，12是车品文体

const catesAll = [{
    name: '精选',
    full_name: '精选',
    cid: 0,
    cid_2: 0
}, {
    name: '女装',
    full_name: '百变女装',
    cid: 1,
    cid_2: 2
}, {
    name: '男装',
    full_name: '品质男装',
    cid: 2,
    cid_2: 6
}, {
    name: '内衣',
    full_name: '舒适内衣',
    cid: 3,
    cid_2: 7
}, {
    name: '美妆',
    full_name: '美妆洗护',
    cid: 4,
    cid_2: 5
}, {
    name: '配饰',
    full_name: '箱包配饰',
    cid: 5,
    cid_2: 8
}, {
    name: '鞋品',
    full_name: '男女鞋靴',
    cid: 6,
    cid_2: 9
}, {
    name: '箱包',
    full_name: '箱包配饰',
    cid: 9,
    cid_2: 8
}, {
    name: '儿童',
    full_name: '母婴童品',
    cid: 10,
    cid_2: 1
}, {
    name: '母婴',
    full_name: '母婴童品',
    cid: 11,
    cid_2: 1
}, {
    name: '居家',
    full_name: '居家日用',
    cid: 12,
    cid_2: 4
}, {
    name: '美食',
    full_name: '食品酒水',
    cid: 13,
    cid_2: 3
}, {
    name: '数码',
    full_name: '数码家电',
    cid: 14,
    cid_2: 11
}, {
    name: '家电',
    full_name: '数码家电',
    cid: 15,
    cid_2: 11
}, {
    name: '其他',
    full_name: '',
    cid: 16,
    cid_2: null
}, {
    name: '车品',
    full_name: '车品文体',
    cid: 17,
    cid_2: 12
}, {
    name: '文体',
    full_name: '车品文体',
    cid: 18,
    cid_2: 12
}, {
    name: '宠物',
    full_name: '宠物用品',
    cid: 19,
    cid_2: 10
}];
export {
    cates,
    catesAll
}